# Generated by Django 4.2.23 on 2025-07-10 19:35

from django.db import migrations, models
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='transactionId',
            field=models.CharField(default=orders.models.generate_transaction_id, editable=False, max_length=50, unique=True),
        ),
    ]
