# Generated by Django 4.2.23 on 2025-07-14 15:02

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[orders.models.validate_kenyan_phone]),
        ),
    ]
