# Generated by Django 4.2.23 on 2025-07-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import otc_sales.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otc_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overthecountersale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overthecountersale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money')], default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='overthecountersale',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='overthecountersale',
            name='trasaction_id',
            field=models.CharField(default=otc_sales.models.generate_transaction_id, max_length=50, unique=True),
        ),
    ]
