# Generated by Django 4.2.23 on 2025-07-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otc_sales', '0002_overthecountersale_cashier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overthecountersale',
            old_name='trasaction_id',
            new_name='transaction_id',
        ),
    ]
