# Generated by Django 4.2.23 on 2025-07-03 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import otc_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otc_sales', '0003_rename_trasaction_id_overthecountersale_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=otc_sales.models.generate_transaction_id, max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money')], default='cash', max_length=50)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='otc_sales.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='OverTheCounterSale',
        ),
    ]
